### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by DBendit** [rgould/dcc_tabbed_sheet#3]
Hey there,

When Roll20 is set to dark mode, rolls are incredibly difficult to see.

Example:
![DarkMode](https://user-images.githubusercontent.com/242696/182516247-c40f762d-5240-41b9-833a-fee7f164bb8c.jpg)
 
Presumably, the CSS for roll text needs to add `@media (prefers-color-scheme: dark)` versions with light-on-dark-friendly colors. I may end up doing this myself, but I figured I'd let you know before I went ahead and threw a PR at you.

-Dave

**Comment by rgould** [comment]
Thanks @DBendit - I agree, those results are impossible to read and I appreciate the heads up! A PR is absolutely welcome :) Let me know if you need any assistance, or if you decide not to do it
